SitemaComando/Models/ErrorViewModel.cs
namespace SitemaComando.Models
    {
        public class ErrorViewModel
        {
            public string? RequestId { get; set; }

            public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
        }
    }

SitemaComando/Models/FuncionarioModel.cs
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Net.NetworkInformation;
using System.Linq;
namespace SitemaComando.Models
{
    public class FuncionarioModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Digite o Nome do Funcionario!")]
        public string Nome { get; set; }
        [Required(ErrorMessage = "Digite o E-mail do Funcionario!")]
        [EmailAddress(ErrorMessage = "o E-mail informado não e valido!")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Digite a pontuação do Funcionario!")]
        public string Pontuacao { get; set; }
       
public class FuncionarioService
    {
        private List<FuncionarioModel> funcionarios;

        public FuncionarioService()
        {
            // Inicialize a lista de funcionários aqui
            funcionarios = new List<FuncionarioModel>();
        }

        public FuncionarioModel ObterFuncionarioComMaiorPontuacao()
        {
            return funcionarios.OrderByDescending(f => int.Parse(f.Pontuacao)).FirstOrDefault();
        }
    }
}
}

SitemaComando/Controllers/FuncionarioController.cs
using SitemaComando.Data;
using SitemaComando.Repositorio;
using Microsoft.AspNetCore.Mvc;
using static System.Runtime.InteropServices.JavaScript.JSType;
using SitemaComando.Models;

namespace MeuSiteEmMVC.Controllers
{
    public class FuncionarioController : Controller { 

 
        private readonly IFuncionarioRepositorio _funcionarioRepositorio;

        public FuncionarioController(IFuncionarioRepositorio funcionarioRepositorio)
        {
            _funcionarioRepositorio = funcionarioRepositorio;
        }

        public IActionResult Index()
        {
            List<FuncionarioModel> funcionarios = _funcionarioRepositorio.BuscarTodos();

            return View(funcionarios);
        }
        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            FuncionarioModel funcionario = _funcionarioRepositorio.ListarPorId(id);

            return View(funcionario);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            FuncionarioModel funcionario = _funcionarioRepositorio.ListarPorId(id);
            return View(funcionario);
        }

        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagado = _funcionarioRepositorio.Apagar(id);

                if (apagado)
                {
                    TempData["MensagemSucesso"] = "funcionario apagado com sucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = $"Ops, não foi possivel apagar o funcionario!";
                }

                return RedirectToAction("Index");

            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não foi possivel apagar o funcionario ,tente novamente!, detalhe do erro:{erro.Message}";
                return RedirectToAction("Index");

            }
        }



        [HttpPost]
        public IActionResult Criar(FuncionarioModel funcionario)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _funcionarioRepositorio.Adicionar(funcionario);
                    TempData["MensagemSucesso"] = "Funcionario cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View(funcionario);

            }
            catch (Exception erro)
            {
                _funcionarioRepositorio.Adicionar(funcionario);
                TempData["MensagemErro"] = $"Ops, não foi possivel casdatrar o funcionario ,tente novamente!, detalhe do erro:{erro.Message}";
                return RedirectToAction("Index");
            }

        }


        [HttpPost]
        public IActionResult Alterar(FuncionarioModel funcionario)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _funcionarioRepositorio.Atualizar(funcionario);
                    TempData["MensagemSucesso"] = "funcionario atualizado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View("Editar", funcionario);

            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não foi possivel atualizar o funcionario ,tente novamente!, detalhe do erro:{erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

SitemaComando/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SitemaComando.Models;
using System.Diagnostics;

namespace MeuSiteEmMVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SitemaComando/Views/Funcionario/ApagarConfirmacao.cshtml
@model FuncionarioModel
@{
    ViewData["Title"] = "Apagar Funcionario ";
}
<div class="text-center">
    <h3> Realmente Deseja Apagar O Funcionario (@Model.Nome)?</h3>
</div>
<a class="btn btn-primary w-100" role="button" asp-controller="Funcionario" asp-action="Index" style="margin-bottom: 5px;">Cancelar Exclusão</a>
<a class="btn btn-danger w-100" role="button" asp-controller="Funcionario" asp-route-id="@Model.Id" asp-action="Apagar">Confirmar Exclusão</a>

SitemaComando/Views/Funcionario/Criar.cshtml
@model FuncionarioModel
@{
    ViewData["Title"] = "Criar Funcionario";
}
<div class="text-center">

    <h1 class="display-4">Cadastrar Funcionario</h1>

</div>
<form asp-controller="Funcionario" asp-action="Criar" method="post">
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Nome Do Funcionario">
        @Html.ValidationMessageFor(x => x.Nome)

    </div>

    <div class="form-group">
        <label for="email">E-mail</label>
        <input type="text" asp-for="Email" class="form-control" placeholder="E-mail Do Funcionario">
        @Html.ValidationMessageFor(x => x.Email)
    </div>

    <div class="form-group">
        <label for="pontuacao">Pontuação</label>
        <input type="text" asp-for="Pontuacao" class="form-control" placeholder="Pontuação Do Funcionario">
        @Html.ValidationMessageFor(x => x.Pontuacao)

    </div>
    <button type="submit" class="btn btn-primary b-block w-100" style="margin-bottom: 5px;">Adicionar</button>

    <a class="btn btn-secondary w-100" asp-controller="Funcionario" asp-action="Index" role="button">Voltar</a>
</form>

SitemaComando/Views/Funcionario/Editar.cshtml
@model FuncionarioModel
@{
    ViewData["Title"] = "Editar Funcionario";
}
<div class="text-center">

    <h1 class="display-4">Editar Funcionario</h1>

</div>
<form asp-controller="Funcionario" asp-action="Alterar" method="post">

    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Nome Do Funcionario">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>


    <div class="form-group">
        <label for="email">Email</label>
        <input type="text" asp-for="Email" class="form-control" placeholder="Email Do Funcionario">
        @Html.ValidationMessageFor(x => x.Email)
    </div>


    <div class="form-group">
        <label for="celular">Celular</label>
        <input type="text" asp-for="Pontuacao" class="form-control" placeholder="Celular Do Funcionario">
        @Html.ValidationMessageFor(x => x.Pontuacao)

    </div>


    <button type="submit" class="btn btn-primary b-block w-100" style="margin-bottom: 5px;">Alterar</button>

    <a class="btn btn-secondary w-100" asp-controller="Funcionario" asp-action="Index" role="button">Voltar</a>
</form>

SitemaComando/Views/Funcionario/Index.cshtml
@model List<FuncionarioModel>
@{
    ViewData["Title"] = "Listagem De Funcionarios";
}
<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-asp-controller="Funcionario" asp-action="Criar">Adicionar Novo Funcionario</a>

    </div>
    <br />


    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class=" btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }
    @if (TempData["MenssagemErro"] != null)
    {

        <div class="alert alert-danger" role="alert">
            <button type="button" class=" btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }

    <br />

    <h1 class="display-4">Listagem De Funcionarios</h1>
    <table class="table" id="table-Funcionario">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>     
                <th scope="col">Email</th>
                <th scope="col">Pontuacao</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (FuncionarioModel Funcionario in Model)
                {
                    <tr>
                        <th scope="row">@Funcionario.Id</th>
                        <td>@Funcionario.Nome</td>
                        <td>@Funcionario.Email</td>
                        <td>@Funcionario.Pontuacao</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@Funcionario.Id" asp-asp-controller="Funcionario" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@Funcionario.Id" asp-asp-controller="Funcionario" asp-action="ApagarConfirmacao">Apagar</a>
                            </div>
                        </td>
                   
                      
                    </tr>
                }
               
            }
        </tbody>
    </table>

    <div>

SitemaComando/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="text-center">
    <br />
    <p>ㅤ</p>
</div>
<!DOCTYPE html>
<html>
<head>
    <title>Top 1 do Ranking</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 80%;
            margin: auto;
            overflow: hidden;
        }

        header {
            background: blue;
            color: white;
            padding-top: 30px;
            min-height: 70px;
            border-bottom: lawngreen 3px solid;
            position: relative; 
            z-index: 1; 
        }

            header h1 {
                padding: 5px 0;
                text-align: center;
            }

        .ranking {
            margin: 20px 0;
            padding: 20px;
            background: white;
            box-shadow: 0px 0px 10px #bbb;
        }

        .top1 {
            font-size: 24px;
            color: darkslategrey;
            text-align: center;
        }

            .top1 img {
                width: 100px;
                height: 100px;
                border-radius: 50%;
            }

        .logo {
            position: absolute; 
            top: 130px;
            left: 143px; 
            width: 80px; 
            height: 100px; 
        }

        .banner { 
            position: absolute; 
            top: -70px;
            left: 10;
            width: 70%; 
            height: 70px; 
            opacity: 1.0; 
            z-index: -1; 
            object-fit:initial;
    
        }

        .nome { 
            color: blue;
            font-weight: bold; 
        }
    </style>
</head>
<body>
    <header>
        <div class="container">
            <h1>Ranking</h1>
            <img class="logo" src="https://scontent.fpoj1-1.fna.fbcdn.net/v/t39.30808-6/305766915_584269483393320_2672217663260485643_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=efb6e6&_nc_ohc=ZO8SPDmnsIIAX9KPehT&_nc_ht=scontent.fpoj1-1.fna&oh=00_AfCW8qr0LAzZY3i9LkQ1ELQYl0j7bnrsxsStVTl7N-P-Gg&oe=656E34AB" alt="Logo"> <!-- adicionei esta linha -->
            <img class="banner" src="https://comandoinformatica.com.br/wp-content/uploads/2022/07/Thg-COMANDO-INFORMATICA_HORIZONTAL_FND_BRANCO.png" alt="Banner"> <!-- adicionei esta linha -->
        </div>
    </header>
    <div class="container">
        <div class="ranking">
            <div class="top1">
                <h2>Top 1</h2>
                <img src="https://comandoinformatica.com.br/wp-content/uploads/2022/08/Matheus900.jpg" alt="Foto do Funcionario">
                <p>Colaborador: <span class="nome">Matheus Figueredo</span></p> 
            </div>
        </div>
    </div>
</body>
</html>

SitemaComando/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SitemaComando</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SitemaComando.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.8/datatables.min.css" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sistema Comando</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Pagina Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Funcionario" asp-action="Index">Funcionarios</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Sistema Comando Informatica
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.8/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>